// SEO-статьи раздела «Блог/Полезное». Тексты под реальные поисковые запросы
// клиентов — это бесплатный органический трафик из Яндекс/Google.
// Каждая статья двуязычная (ru/en). Для fr/de/ja/ar/he показывается англ. версия
// (как и остальной «тяжёлый» контент платформы).

export type LocaleStr = { ru: string; en: string };

export type BlogBlock =
  | { type: "p"; text: LocaleStr }
  | { type: "h"; text: LocaleStr }
  | { type: "li"; items: LocaleStr[] };

export type BlogAudience = "client" | "provider";

export type BlogPost = {
  slug: string;
  icon: string;
  date: string;
  readMin: number;
  // Для кого статья: "client" — для заказчиков услуг, "provider" — для специалистов.
  audience: BlogAudience;
  title: LocaleStr;
  excerpt: LocaleStr;
  // SEO мета для конкретной статьи
  metaTitle: LocaleStr;
  metaDescription: LocaleStr;
  body: BlogBlock[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "how-to-choose-private-detective",
    icon: "Search",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: {
      ru: "Как выбрать частного детектива: полное руководство",
      en: "How to choose a private detective: a complete guide",
    },
    excerpt: {
      ru: "На что смотреть при выборе частного детектива, какие документы проверять и как не попасть к мошеннику.",
      en: "What to look for when choosing a private detective, which documents to check and how to avoid scammers.",
    },
    metaTitle: {
      ru: "Как выбрать частного детектива — критерии, документы, цены | ЩИТ",
      en: "How to choose a private detective — criteria, documents, prices | SHCHIT",
    },
    metaDescription: {
      ru: "Пошаговое руководство по выбору частного детектива: лицензия, опыт, договор, цены и признаки мошенников. Проверенные специалисты на платформе ЩИТ.",
      en: "Step-by-step guide to choosing a private detective: license, experience, contract, prices and scam red flags. Verified specialists on SHCHIT.",
    },
    body: [
      { type: "p", text: {
        ru: "Частный детектив помогает в ситуациях, где нужна аккуратная и законная работа с информацией: поиск людей, проверка контрагентов, сбор доказательств. Ошибка в выборе стоит дорого — и денег, и времени. Разберём, как выбрать специалиста, которому можно доверять.",
        en: "A private detective helps in situations that require careful and lawful work with information: locating people, vetting counterparties, gathering evidence. Choosing wrong is costly — in money and time. Let's break down how to pick a specialist you can trust.",
      } },
      { type: "h", text: { ru: "1. Проверьте лицензию и статус", en: "1. Check the license and legal status" } },
      { type: "p", text: {
        ru: "В большинстве стран частная детективная деятельность лицензируется. Попросите номер лицензии и подтверждение статуса ИП или компании. На платформе ЩИТ значок «Лицензия» появляется только после проверки документов модератором.",
        en: "In most countries private investigation is licensed. Ask for the license number and confirmation of sole-proprietor or company status. On SHCHIT, the 'License' badge appears only after a moderator verifies the documents.",
      } },
      { type: "h", text: { ru: "2. Оцените опыт и специализацию", en: "2. Assess experience and specialization" } },
      { type: "p", text: {
        ru: "Детективы часто специализируются: одни сильны в корпоративных расследованиях, другие — в поиске людей или семейных делах. Спросите про похожие кейсы и результат.",
        en: "Detectives often specialize: some are strong in corporate investigations, others in locating people or family matters. Ask about similar cases and outcomes.",
      } },
      { type: "h", text: { ru: "3. Обязательно заключайте договор", en: "3. Always sign a contract" } },
      { type: "p", text: {
        ru: "Договор фиксирует объём работ, сроки, стоимость и законные рамки. Отказ работать по договору — тревожный сигнал.",
        en: "A contract fixes the scope, timeline, cost and legal boundaries. Refusing to work under a contract is a red flag.",
      } },
      { type: "h", text: { ru: "Признаки мошенника", en: "Scam red flags" } },
      { type: "li", items: [
        { ru: "Обещает «стопроцентный результат» по любому делу", en: "Promises a '100% result' on any case" },
        { ru: "Требует всю оплату вперёд наличными без документов", en: "Demands full prepayment in cash with no paperwork" },
        { ru: "Отказывается показывать лицензию и заключать договор", en: "Refuses to show a license or sign a contract" },
        { ru: "Предлагает заведомо незаконные методы", en: "Offers clearly illegal methods" },
      ] },
      { type: "p", text: {
        ru: "Вывод: проверяйте лицензию, работайте по договору и выбирайте специалистов с подтверждённой репутацией. На платформе ЩИТ все специалисты проходят проверку, а рейтинг и отзывы помогают принять решение.",
        en: "Bottom line: verify the license, work under a contract, and choose specialists with a proven reputation. On SHCHIT every specialist is verified, and ratings and reviews help you decide.",
      } },
    ],
  },
  {
    slug: "how-much-bodyguard-costs",
    icon: "Shield",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: {
      ru: "Сколько стоит телохранитель и от чего зависит цена",
      en: "How much a bodyguard costs and what affects the price",
    },
    excerpt: {
      ru: "Разбираем реальные цены на услуги личной охраны: почасовая, посуточная и постоянная защита.",
      en: "A breakdown of real personal protection prices: hourly, daily and full-time security.",
    },
    metaTitle: {
      ru: "Сколько стоит телохранитель — цены на личную охрану 2026 | ЩИТ",
      en: "How much a bodyguard costs — personal security prices 2026 | SHCHIT",
    },
    metaDescription: {
      ru: "Реальные цены на услуги телохранителя: от чего зависит стоимость, форматы охраны и как сэкономить без потери качества. Проверенные специалисты на ЩИТ.",
      en: "Real bodyguard prices: what affects the cost, protection formats and how to save without losing quality. Verified specialists on SHCHIT.",
    },
    body: [
      { type: "p", text: {
        ru: "Стоимость услуг телохранителя зависит от уровня риска, квалификации специалиста, продолжительности и формата защиты. Разберём, из чего складывается цена и как выбрать оптимальный вариант.",
        en: "The cost of a bodyguard depends on the risk level, the specialist's qualifications, duration and protection format. Let's see what makes up the price and how to choose the best option.",
      } },
      { type: "h", text: { ru: "Что влияет на цену", en: "What affects the price" } },
      { type: "li", items: [
        { ru: "Уровень угрозы и публичность клиента", en: "Threat level and the client's public profile" },
        { ru: "Опыт, лицензия и подготовка специалиста", en: "The specialist's experience, license and training" },
        { ru: "Формат: разовое сопровождение или постоянная защита", en: "Format: one-off escort or full-time protection" },
        { ru: "Количество охранников и наличие автомобиля", en: "Number of guards and whether a vehicle is provided" },
      ] },
      { type: "h", text: { ru: "Форматы оплаты", en: "Payment formats" } },
      { type: "p", text: {
        ru: "Обычно услуги считают почасово (короткое сопровождение), посуточно (мероприятие, поездка) или помесячно (постоянная защита). Помесячный формат чаще выгоднее в пересчёте на час.",
        en: "Services are usually priced hourly (short escort), daily (an event or trip) or monthly (full-time protection). The monthly format is often cheaper per hour.",
      } },
      { type: "p", text: {
        ru: "Совет: не выбирайте охрану только по низкой цене. Проверяйте лицензию, подготовку и отзывы. На платформе ЩИТ вы видите подтверждённый статус специалиста и его рейтинг.",
        en: "Tip: don't choose security by low price alone. Check the license, training and reviews. On SHCHIT you can see a specialist's verified status and rating.",
      } },
    ],
  },
  {
    slug: "how-polygraph-test-works",
    icon: "Activity",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: {
      ru: "Как проходит проверка на полиграфе (детекторе лжи)",
      en: "How a polygraph (lie detector) test works",
    },
    excerpt: {
      ru: "Что такое полиграф, как проходит проверка, можно ли обмануть детектор и что учитывать при заказе.",
      en: "What a polygraph is, how the test goes, whether you can beat it and what to consider when booking.",
    },
    metaTitle: {
      ru: "Как проходит проверка на полиграфе — этапы, цена, точность | ЩИТ",
      en: "How a polygraph test works — steps, price, accuracy | SHCHIT",
    },
    metaDescription: {
      ru: "Подробно о проверке на полиграфе: этапы, подготовка, точность, стоимость и как выбрать полиграфолога. Проверенные специалисты на платформе ЩИТ.",
      en: "In detail about polygraph testing: steps, preparation, accuracy, cost and how to choose an examiner. Verified specialists on SHCHIT.",
    },
    body: [
      { type: "p", text: {
        ru: "Полиграф фиксирует физиологические реакции человека на вопросы. Его применяют при найме, служебных проверках и в частных ситуациях. Разберём, как проходит проверка и на что обратить внимание.",
        en: "A polygraph records a person's physiological reactions to questions. It's used in hiring, internal investigations and private situations. Let's look at how the test goes and what matters.",
      } },
      { type: "h", text: { ru: "Этапы проверки", en: "Test stages" } },
      { type: "li", items: [
        { ru: "Предтестовая беседа: обсуждение вопросов и согласие", en: "Pre-test interview: discussing the questions and consent" },
        { ru: "Основной этап: регистрация реакций на вопросы", en: "Main stage: recording reactions to questions" },
        { ru: "Анализ данных и заключение полиграфолога", en: "Data analysis and the examiner's conclusion" },
      ] },
      { type: "h", text: { ru: "Точность и ограничения", en: "Accuracy and limitations" } },
      { type: "p", text: {
        ru: "Результат сильно зависит от квалификации специалиста и корректной методики. Поэтому важно выбирать опытного полиграфолога с подтверждённой подготовкой.",
        en: "The result strongly depends on the examiner's qualifications and a correct methodology. That's why it's important to choose an experienced examiner with verified training.",
      } },
      { type: "p", text: {
        ru: "На платформе ЩИТ можно выбрать полиграфолога с проверенными документами, изучить отзывы и связаться напрямую без посредников.",
        en: "On SHCHIT you can choose a polygraph examiner with verified documents, read reviews and contact them directly without intermediaries.",
      } },
    ],
  },
  {
    slug: "how-to-verify-security-specialist",
    icon: "BadgeCheck",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: {
      ru: "Как проверить специалиста по безопасности перед заказом",
      en: "How to verify a security specialist before hiring",
    },
    excerpt: {
      ru: "Простой чек-лист проверки любого специалиста по безопасности: документы, репутация, договор.",
      en: "A simple checklist to verify any security specialist: documents, reputation, contract.",
    },
    metaTitle: {
      ru: "Как проверить специалиста по безопасности — чек-лист | ЩИТ",
      en: "How to verify a security specialist — checklist | SHCHIT",
    },
    metaDescription: {
      ru: "Чек-лист проверки специалиста по безопасности: лицензия, статус, репутация, договор и признаки мошенников. Проверенные профессионалы на платформе ЩИТ.",
      en: "Checklist to verify a security specialist: license, status, reputation, contract and scam signs. Verified professionals on SHCHIT.",
    },
    body: [
      { type: "p", text: {
        ru: "Перед тем как доверить деликатное дело, важно убедиться в надёжности специалиста. Вот короткий чек-лист, который защитит вас от ошибок.",
        en: "Before trusting someone with a sensitive matter, make sure the specialist is reliable. Here's a short checklist that protects you from mistakes.",
      } },
      { type: "h", text: { ru: "Чек-лист проверки", en: "Verification checklist" } },
      { type: "li", items: [
        { ru: "Лицензия и правовой статус (ИП/компания)", en: "License and legal status (sole proprietor/company)" },
        { ru: "Реальные отзывы и рейтинг", en: "Genuine reviews and rating" },
        { ru: "Готовность заключить договор", en: "Willingness to sign a contract" },
        { ru: "Прозрачное ценообразование без скрытых платежей", en: "Transparent pricing with no hidden fees" },
        { ru: "Специализация под вашу задачу", en: "Specialization matching your task" },
      ] },
      { type: "p", text: {
        ru: "Платформа ЩИТ берёт часть проверки на себя: значок «Лицензия» выдаётся только после подтверждения документов, а рейтинг и отзывы формируют прозрачную репутацию.",
        en: "SHCHIT takes part of the verification off your shoulders: the 'License' badge is issued only after documents are confirmed, while ratings and reviews build a transparent reputation.",
      } },
    ],
  },
  {
    slug: "what-is-tscm-bug-sweeping",
    icon: "Radar",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: {
      ru: "Что такое поиск прослушки (TSCM) и когда он нужен",
      en: "What is bug sweeping (TSCM) and when you need it",
    },
    excerpt: {
      ru: "Когда стоит заказать проверку помещения на прослушку, как проходит поиск устройств и что важно знать.",
      en: "When to order a room sweep for bugs, how device detection works and what to know.",
    },
    metaTitle: {
      ru: "Поиск прослушки (TSCM) — что это, когда нужно, цена | ЩИТ",
      en: "Bug sweeping (TSCM) — what it is, when you need it, price | SHCHIT",
    },
    metaDescription: {
      ru: "Поиск прослушки и скрытых камер (TSCM): когда заказывать, как проходит проверка помещения и как выбрать специалиста. Проверенные эксперты на платформе ЩИТ.",
      en: "Bug and hidden-camera sweeping (TSCM): when to order, how a room check works and how to choose a specialist. Verified experts on SHCHIT.",
    },
    body: [
      { type: "p", text: {
        ru: "TSCM — это профессиональный поиск скрытых устройств прослушки и наблюдения. Его заказывают, когда есть риск утечки информации или слежки.",
        en: "TSCM is the professional search for hidden listening and surveillance devices. It's ordered when there's a risk of information leaks or surveillance.",
      } },
      { type: "h", text: { ru: "Когда стоит заказать проверку", en: "When to order a sweep" } },
      { type: "li", items: [
        { ru: "Перед важными переговорами и сделками", en: "Before important negotiations and deals" },
        { ru: "При подозрении на утечку конфиденциальной информации", en: "When you suspect a leak of confidential information" },
        { ru: "После визита посторонних в офис или дом", en: "After strangers have visited your office or home" },
      ] },
      { type: "p", text: {
        ru: "Проверку должны проводить специалисты со специальным оборудованием. На платформе ЩИТ можно найти проверенных экспертов по технической безопасности с подтверждённой квалификацией.",
        en: "The sweep should be done by specialists with dedicated equipment. On SHCHIT you can find verified technical-security experts with confirmed qualifications.",
      } },
    ],
  },
  {
    slug: "how-to-check-counterparty-before-deal",
    icon: "Building2",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как проверить контрагента перед сделкой", en: "How to vet a counterparty before a deal" },
    excerpt: { ru: "Законные способы проверить компанию или партнёра перед подписанием договора и снизить риски.", en: "Legal ways to check a company or partner before signing a contract and reduce risks." },
    metaTitle: { ru: "Как проверить контрагента перед сделкой — чек-лист | ЩИТ", en: "How to vet a counterparty before a deal — checklist | SHCHIT" },
    metaDescription: { ru: "Проверка контрагента законными методами: реестры, финансы, репутация, признаки фирм-однодневок. Помощь проверенных специалистов на платформе ЩИТ.", en: "Vetting a counterparty by legal means: registries, finances, reputation, shell-company red flags. Help from verified specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Проверка контрагента перед сделкой — это законная и обязательная практика для бизнеса. Она защищает от мошенников, неплатежей и юридических рисков.", en: "Vetting a counterparty before a deal is a legal and essential business practice. It protects against fraudsters, non-payment and legal risks." } },
      { type: "h", text: { ru: "Что проверить", en: "What to check" } },
      { type: "li", items: [
        { ru: "Регистрационные данные в официальных реестрах", en: "Registration data in official registries" },
        { ru: "Финансовое состояние и задолженности", en: "Financial condition and debts" },
        { ru: "Судебные дела и репутацию", en: "Court cases and reputation" },
        { ru: "Полномочия подписанта договора", en: "The signatory's authority" },
      ] },
      { type: "p", text: { ru: "Специалисты по экономической безопасности проведут проверку глубже и подготовят заключение. Найти таких экспертов можно в каталоге ЩИТ.", en: "Economic-security specialists can dig deeper and prepare a report. You can find such experts in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "how-to-find-missing-person-legally",
    icon: "MapPin",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как законно найти пропавшего человека или родственника", en: "How to legally find a missing person or relative" },
    excerpt: { ru: "Пошаговый план законного поиска человека: куда обращаться и как помогает частный детектив.", en: "A step-by-step plan for a lawful person search: where to turn and how a private detective helps." },
    metaTitle: { ru: "Как найти пропавшего человека законно — пошагово | ЩИТ", en: "How to find a missing person legally — step by step | SHCHIT" },
    metaDescription: { ru: "Законный поиск пропавшего человека или потерянного родственника: заявление, официальные каналы и помощь частного детектива. Проверенные специалисты на ЩИТ.", en: "Lawful search for a missing person or lost relative: statement, official channels and help from a private detective. Verified specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Поиск пропавшего человека или потерянного родственника — законная услуга, если она ведётся в рамках закона и без нарушения прав третьих лиц.", en: "Searching for a missing person or lost relative is a lawful service when conducted within the law and without violating third parties' rights." } },
      { type: "h", text: { ru: "С чего начать", en: "Where to start" } },
      { type: "li", items: [
        { ru: "Официальное обращение в компетентные органы", en: "An official request to the competent authorities" },
        { ru: "Сбор всей известной информации о человеке", en: "Collecting all known information about the person" },
        { ru: "Обращение к лицензированному частному детективу", en: "Turning to a licensed private detective" },
      ] },
      { type: "p", text: { ru: "Частный детектив работает легальными методами и дополняет усилия официальных структур. Проверенных специалистов можно найти на платформе ЩИТ.", en: "A private detective works by legal methods and complements official efforts. Verified specialists can be found on SHCHIT." } },
    ],
  },
  {
    slug: "employee-background-check",
    icon: "UserCheck",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Проверка сотрудника при приёме на работу", en: "Employee background check when hiring" },
    excerpt: { ru: "Как законно проверить кандидата перед наймом и защитить компанию от рисков.", en: "How to legally check a candidate before hiring and protect the company from risks." },
    metaTitle: { ru: "Проверка сотрудника при приёме на работу — как и что | ЩИТ", en: "Employee background check when hiring — how and what | SHCHIT" },
    metaDescription: { ru: "Законная проверка кандидата: подлинность документов, опыт, репутация, согласие на обработку данных. Помощь специалистов по безопасности на платформе ЩИТ.", en: "Legal candidate check: document authenticity, experience, reputation, consent to data processing. Help from security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Проверка кандидата при найме законна при согласии человека на обработку его данных. Это снижает риски для бизнеса и коллектива.", en: "Checking a candidate when hiring is legal with the person's consent to process their data. It reduces risks for the business and the team." } },
      { type: "h", text: { ru: "Что обычно проверяют", en: "What is usually checked" } },
      { type: "li", items: [
        { ru: "Подлинность документов и образования", en: "Authenticity of documents and education" },
        { ru: "Реальный опыт и рекомендации", en: "Actual experience and references" },
        { ru: "Деловую репутацию (в рамках закона)", en: "Business reputation (within the law)" },
      ] },
      { type: "p", text: { ru: "Важно: проверка проводится только с согласия кандидата. Специалистов по кадровой безопасности вы найдёте в каталоге ЩИТ.", en: "Important: the check is done only with the candidate's consent. You can find HR-security specialists in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "how-to-protect-home-from-burglary",
    icon: "Home",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как защитить дом и квартиру от взлома", en: "How to protect your home from burglary" },
    excerpt: { ru: "Практические меры безопасности жилья: сигнализация, замки, освещение и организационные привычки.", en: "Practical home security measures: alarms, locks, lighting and organizational habits." },
    metaTitle: { ru: "Как защитить дом от взлома — практические меры | ЩИТ", en: "How to protect your home from burglary — practical steps | SHCHIT" },
    metaDescription: { ru: "Как защитить квартиру и дом от взлома: сигнализация, надёжные замки, видеонаблюдение и привычки. Консультация специалистов по безопасности на платформе ЩИТ.", en: "How to protect your home from burglary: alarms, reliable locks, CCTV and habits. Security specialist consultation on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Большинство взломов можно предотвратить простыми мерами. Разберём, что реально работает.", en: "Most burglaries can be prevented with simple measures. Let's look at what actually works." } },
      { type: "h", text: { ru: "Базовые меры", en: "Basic measures" } },
      { type: "li", items: [
        { ru: "Надёжные замки и укреплённая дверь", en: "Reliable locks and a reinforced door" },
        { ru: "Сигнализация и видеонаблюдение", en: "Alarm and video surveillance" },
        { ru: "Датчики движения и освещение", en: "Motion sensors and lighting" },
        { ru: "Не афишировать отъезды в соцсетях", en: "Not advertising your trips on social media" },
      ] },
      { type: "p", text: { ru: "Для комплексной защиты закажите аудит безопасности жилья у специалиста. Найти эксперта можно на платформе ЩИТ.", en: "For comprehensive protection, order a home security audit from a specialist. You can find an expert on SHCHIT." } },
    ],
  },
  {
    slug: "personal-cybersecurity-basics",
    icon: "Lock",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Основы личной кибербезопасности: защита данных и денег", en: "Personal cybersecurity basics: protecting data and money" },
    excerpt: { ru: "Простые правила, которые защитят ваши аккаунты, деньги и личные данные от мошенников.", en: "Simple rules that protect your accounts, money and personal data from fraudsters." },
    metaTitle: { ru: "Основы личной кибербезопасности — защита данных | ЩИТ", en: "Personal cybersecurity basics — data protection | SHCHIT" },
    metaDescription: { ru: "Личная кибербезопасность: надёжные пароли, двухфакторная защита, распознавание фишинга и мошенников. Помощь экспертов по кибербезопасности на платформе ЩИТ.", en: "Personal cybersecurity: strong passwords, two-factor auth, spotting phishing and scams. Help from cybersecurity experts on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Большинство краж данных и денег происходит из-за простых ошибок пользователя. Несколько привычек резко снижают риск.", en: "Most data and money theft happens due to simple user mistakes. A few habits sharply reduce the risk." } },
      { type: "h", text: { ru: "Обязательный минимум", en: "The essential minimum" } },
      { type: "li", items: [
        { ru: "Уникальные надёжные пароли и менеджер паролей", en: "Unique strong passwords and a password manager" },
        { ru: "Двухфакторная аутентификация везде, где можно", en: "Two-factor authentication wherever possible" },
        { ru: "Осторожность с ссылками и вложениями (фишинг)", en: "Caution with links and attachments (phishing)" },
        { ru: "Регулярные обновления устройств", en: "Regular device updates" },
      ] },
      { type: "p", text: { ru: "Если вы уже столкнулись с мошенничеством или взломом, обратитесь к специалисту по кибербезопасности на платформе ЩИТ.", en: "If you've already faced fraud or a hack, contact a cybersecurity specialist on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-recognize-phone-scam",
    icon: "PhoneOff",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как распознать телефонных и онлайн-мошенников", en: "How to recognize phone and online scammers" },
    excerpt: { ru: "Типичные схемы мошенников и признаки, по которым их можно вычислить до потери денег.", en: "Typical scam schemes and signs that help you spot them before losing money." },
    metaTitle: { ru: "Как распознать мошенников — схемы и признаки | ЩИТ", en: "How to recognize scammers — schemes and signs | SHCHIT" },
    metaDescription: { ru: "Как распознать телефонных и онлайн-мошенников: типичные схемы, признаки обмана и что делать. Консультация специалистов по безопасности на платформе ЩИТ.", en: "How to recognize phone and online scammers: typical schemes, signs of deception and what to do. Security specialist advice on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Мошенники давят на эмоции: страх, срочность, жадность. Зная схемы, вы легко их распознаете.", en: "Scammers press on emotions: fear, urgency, greed. Knowing the schemes, you'll easily recognize them." } },
      { type: "h", text: { ru: "Тревожные признаки", en: "Warning signs" } },
      { type: "li", items: [
        { ru: "Срочно требуют перевести деньги или назвать коды", en: "Urgently demand money transfers or codes" },
        { ru: "Представляются банком, полицией, госорганом", en: "Impersonate a bank, police or a government body" },
        { ru: "Запугивают или обещают лёгкую выгоду", en: "Intimidate you or promise easy gains" },
      ] },
      { type: "p", text: { ru: "Правило: положите трубку и перезвоните в организацию по официальному номеру. При крупном ущербе поможет специалист по безопасности с платформы ЩИТ.", en: "Rule: hang up and call the organization back on its official number. For major losses, a security specialist from SHCHIT can help." } },
    ],
  },
  {
    slug: "corporate-security-audit",
    icon: "Briefcase",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Аудит безопасности бизнеса: зачем и как проводится", en: "Business security audit: why and how it's done" },
    excerpt: { ru: "Что такое аудит корпоративной безопасности, какие угрозы выявляет и как заказать.", en: "What a corporate security audit is, what threats it uncovers and how to order one." },
    metaTitle: { ru: "Аудит безопасности бизнеса — что это и зачем | ЩИТ", en: "Business security audit — what it is and why | SHCHIT" },
    metaDescription: { ru: "Аудит корпоративной безопасности: физическая, экономическая и информационная защита компании. Проверенные специалисты по безопасности на платформе ЩИТ.", en: "Corporate security audit: physical, economic and information protection of a company. Verified security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Аудит безопасности выявляет слабые места компании до того, как ими воспользуются злоумышленники или конкуренты.", en: "A security audit uncovers a company's weak spots before criminals or competitors exploit them." } },
      { type: "h", text: { ru: "Что охватывает аудит", en: "What the audit covers" } },
      { type: "li", items: [
        { ru: "Физическую безопасность объектов", en: "Physical security of premises" },
        { ru: "Экономическую и кадровую безопасность", en: "Economic and HR security" },
        { ru: "Информационную защиту и утечки данных", en: "Information protection and data leaks" },
      ] },
      { type: "p", text: { ru: "Комплексный аудит проводят специалисты по корпоративной безопасности. Найти их можно в каталоге ЩИТ.", en: "A comprehensive audit is done by corporate-security specialists. You can find them in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "event-security-organization",
    icon: "Users",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как организовать охрану мероприятия", en: "How to organize event security" },
    excerpt: { ru: "Что учесть при заказе охраны для мероприятия: количество людей, риски, документы.", en: "What to consider when hiring security for an event: crowd size, risks, documents." },
    metaTitle: { ru: "Охрана мероприятия — как организовать и сколько стоит | ЩИТ", en: "Event security — how to organize and what it costs | SHCHIT" },
    metaDescription: { ru: "Как организовать охрану мероприятия: оценка рисков, количество охранников, контроль доступа и документы. Проверенные охранные специалисты на платформе ЩИТ.", en: "How to organize event security: risk assessment, number of guards, access control and documents. Verified security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Безопасность мероприятия начинается с планирования. Чем раньше вы привлечёте специалистов, тем спокойнее пройдёт событие.", en: "Event safety starts with planning. The earlier you involve specialists, the calmer the event will go." } },
      { type: "h", text: { ru: "Что важно учесть", en: "What matters" } },
      { type: "li", items: [
        { ru: "Оценку рисков и число гостей", en: "Risk assessment and number of guests" },
        { ru: "Контроль доступа и досмотр", en: "Access control and screening" },
        { ru: "Согласование с площадкой и документы", en: "Coordination with the venue and documents" },
      ] },
      { type: "p", text: { ru: "Опытные охранные специалисты возьмут организацию на себя. Найдите их в каталоге ЩИТ.", en: "Experienced security specialists will handle the organization. Find them in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "how-to-check-car-before-buying",
    icon: "Car",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как проверить автомобиль перед покупкой", en: "How to check a car before buying" },
    excerpt: { ru: "Законные способы проверить историю и юридическую чистоту авто, чтобы не купить проблему.", en: "Legal ways to check a car's history and legal status so you don't buy a problem." },
    metaTitle: { ru: "Как проверить авто перед покупкой — история и чистота | ЩИТ", en: "How to check a car before buying — history and legality | SHCHIT" },
    metaDescription: { ru: "Проверка автомобиля перед покупкой: история, залоги, ограничения, юридическая чистота. Помощь специалистов по проверке имущества на платформе ЩИТ.", en: "Checking a car before buying: history, liens, restrictions, legal status. Help from asset-verification specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Покупка автомобиля с «сюрпризами» оборачивается потерей денег. Проверка истории и юридической чистоты защищает сделку.", en: "Buying a car with hidden 'surprises' leads to lost money. Checking history and legal status protects the deal." } },
      { type: "h", text: { ru: "Что проверить", en: "What to check" } },
      { type: "li", items: [
        { ru: "Историю ДТП и пробег", en: "Accident history and mileage" },
        { ru: "Залоги, аресты и ограничения", en: "Liens, seizures and restrictions" },
        { ru: "Совпадение документов и номеров", en: "Matching documents and numbers" },
      ] },
      { type: "p", text: { ru: "Специалисты по проверке имущества помогут не ошибиться. Найти их можно на платформе ЩИТ.", en: "Asset-verification specialists will help you avoid mistakes. Find them on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-check-real-estate-before-buying",
    icon: "Key",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как проверить недвижимость перед покупкой", en: "How to check real estate before buying" },
    excerpt: { ru: "Юридическая проверка квартиры или дома: собственники, обременения, история сделок.", en: "Legal check of an apartment or house: owners, encumbrances, transaction history." },
    metaTitle: { ru: "Проверка недвижимости перед покупкой — чек-лист | ЩИТ", en: "Checking real estate before buying — checklist | SHCHIT" },
    metaDescription: { ru: "Юридическая проверка недвижимости: собственники, обременения, аресты, история сделок и риски. Помощь специалистов по безопасности сделок на платформе ЩИТ.", en: "Legal real-estate check: owners, encumbrances, seizures, transaction history and risks. Help from deal-security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Недвижимость — крупная покупка, где ошибка стоит особенно дорого. Юридическая проверка снижает риски оспаривания сделки.", en: "Real estate is a major purchase where a mistake is especially costly. A legal check reduces the risk of the deal being challenged." } },
      { type: "h", text: { ru: "Что проверяют", en: "What is checked" } },
      { type: "li", items: [
        { ru: "Право собственности и историю переходов", en: "Ownership and transfer history" },
        { ru: "Обременения, аресты и залоги", en: "Encumbrances, seizures and liens" },
        { ru: "Права третьих лиц и прописанных", en: "Rights of third parties and registered residents" },
      ] },
      { type: "p", text: { ru: "Проверку проведут специалисты по безопасности сделок с недвижимостью. Найдите их в каталоге ЩИТ.", en: "The check is done by real-estate deal-security specialists. Find them in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "children-online-safety",
    icon: "Baby",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как защитить ребёнка в интернете", en: "How to keep your child safe online" },
    excerpt: { ru: "Практические меры родительского контроля и цифровой безопасности для детей.", en: "Practical parental-control and digital-safety measures for children." },
    metaTitle: { ru: "Как защитить ребёнка в интернете — советы родителям | ЩИТ", en: "How to keep your child safe online — parent tips | SHCHIT" },
    metaDescription: { ru: "Цифровая безопасность детей: родительский контроль, приватность, защита от опасного контента и мошенников. Консультация специалистов на платформе ЩИТ.", en: "Children's digital safety: parental controls, privacy, protection from harmful content and scammers. Specialist advice on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Дети активно пользуются интернетом, и их безопасность зависит от правильных настроек и доверительного разговора.", en: "Children use the internet actively, and their safety depends on the right settings and an open conversation." } },
      { type: "h", text: { ru: "Что сделать", en: "What to do" } },
      { type: "li", items: [
        { ru: "Настроить родительский контроль на устройствах", en: "Set up parental controls on devices" },
        { ru: "Обсудить приватность и опасных «знакомых»", en: "Discuss privacy and dangerous 'acquaintances'" },
        { ru: "Научить распознавать мошенников и травлю", en: "Teach how to spot scammers and bullying" },
      ] },
      { type: "p", text: { ru: "Специалисты по кибербезопасности помогут настроить защиту и разобрать инциденты. Найдите их на платформе ЩИТ.", en: "Cybersecurity specialists will help set up protection and handle incidents. Find them on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-protect-personal-data",
    icon: "ShieldCheck",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как защитить персональные данные от утечек", en: "How to protect personal data from leaks" },
    excerpt: { ru: "Что делать, чтобы ваши данные не попали к мошенникам, и как действовать при утечке.", en: "What to do so your data doesn't reach fraudsters and how to act after a leak." },
    metaTitle: { ru: "Как защитить персональные данные — практические меры | ЩИТ", en: "How to protect personal data — practical measures | SHCHIT" },
    metaDescription: { ru: "Защита персональных данных: минимизация цифрового следа, настройки приватности и действия при утечке. Помощь экспертов по безопасности на платформе ЩИТ.", en: "Personal data protection: minimizing your digital footprint, privacy settings and steps after a leak. Help from security experts on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Чем меньше лишних данных о вас в открытом доступе, тем сложнее мошенникам. Контроль цифрового следа — базовая гигиена.", en: "The less unnecessary data about you is public, the harder it is for fraudsters. Controlling your digital footprint is basic hygiene." } },
      { type: "h", text: { ru: "Базовые шаги", en: "Basic steps" } },
      { type: "li", items: [
        { ru: "Проверить настройки приватности в сервисах", en: "Review privacy settings in services" },
        { ru: "Не публиковать лишнее о себе и близких", en: "Don't overshare about yourself and family" },
        { ru: "Отслеживать утечки и менять пароли", en: "Monitor leaks and change passwords" },
      ] },
      { type: "p", text: { ru: "При серьёзной утечке обратитесь к специалисту по защите данных на платформе ЩИТ.", en: "In case of a serious leak, contact a data-protection specialist on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-behave-in-dangerous-situation",
    icon: "AlertTriangle",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как вести себя в опасной ситуации на улице", en: "How to act in a dangerous situation on the street" },
    excerpt: { ru: "Базовые правила личной безопасности, которые помогут избежать конфликта и остаться невредимым.", en: "Basic personal-safety rules that help avoid conflict and stay unharmed." },
    metaTitle: { ru: "Личная безопасность на улице — правила поведения | ЩИТ", en: "Personal safety on the street — rules of conduct | SHCHIT" },
    metaDescription: { ru: "Личная безопасность: как избежать конфликта, вести себя при угрозе и снизить риски на улице. Обучение и консультации специалистов на платформе ЩИТ.", en: "Personal safety: how to avoid conflict, behave under threat and reduce street risks. Training and consultations from specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Лучшая защита — не попадать в опасную ситуацию. Внимательность и простые правила снижают риски.", en: "The best defense is avoiding a dangerous situation. Awareness and simple rules reduce risks." } },
      { type: "h", text: { ru: "Правила безопасности", en: "Safety rules" } },
      { type: "li", items: [
        { ru: "Избегать безлюдных и тёмных мест", en: "Avoid deserted and dark places" },
        { ru: "Сохранять дистанцию и не провоцировать", en: "Keep distance and don't provoke" },
        { ru: "При угрозе — приоритет жизни, а не вещей", en: "Under threat, prioritize life over belongings" },
      ] },
      { type: "p", text: { ru: "Навыки личной безопасности можно освоить у инструкторов и телохранителей на платформе ЩИТ.", en: "Personal-safety skills can be learned from instructors and bodyguards on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-find-lawyer-security-case",
    icon: "Scale",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Когда нужен юрист вместе со специалистом по безопасности", en: "When you need a lawyer alongside a security specialist" },
    excerpt: { ru: "В каких делах связка «детектив + юрист» даёт лучший результат и как её организовать.", en: "In which matters the 'detective + lawyer' combo works best and how to arrange it." },
    metaTitle: { ru: "Детектив и юрист вместе — когда это нужно | ЩИТ", en: "Detective and lawyer together — when it's needed | SHCHIT" },
    metaDescription: { ru: "Когда для дела нужна связка детектива и юриста: сбор доказательств, споры, защита интересов в суде. Проверенные специалисты на платформе ЩИТ.", en: "When a case needs a detective-and-lawyer combo: evidence gathering, disputes, protecting interests in court. Verified specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Детектив собирает факты законными методами, а юрист превращает их в правовую позицию. Вместе они эффективнее.", en: "A detective gathers facts by legal means, and a lawyer turns them into a legal position. Together they're more effective." } },
      { type: "h", text: { ru: "Когда это нужно", en: "When it's needed" } },
      { type: "li", items: [
        { ru: "Семейные и наследственные споры", en: "Family and inheritance disputes" },
        { ru: "Взыскание долгов и защита бизнеса", en: "Debt recovery and business protection" },
        { ru: "Сбор доказательств для суда", en: "Gathering evidence for court" },
      ] },
      { type: "p", text: { ru: "На платформе ЩИТ можно найти и детектива, и смежных специалистов для комплексного решения задачи.", en: "On SHCHIT you can find both a detective and related specialists for a comprehensive solution." } },
    ],
  },
  {
    slug: "how-to-collect-evidence-legally",
    icon: "FileSearch",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как законно собрать доказательства для суда", en: "How to legally gather evidence for court" },
    excerpt: { ru: "Какие доказательства принимает суд и как их собрать без нарушения закона.", en: "What evidence courts accept and how to gather it without breaking the law." },
    metaTitle: { ru: "Как собрать доказательства для суда законно | ЩИТ", en: "How to gather court evidence legally | SHCHIT" },
    metaDescription: { ru: "Законный сбор доказательств для суда: допустимость, оформление, помощь детектива и юриста. Проверенные специалисты на платформе ЩИТ.", en: "Legal gathering of court evidence: admissibility, documentation, help from a detective and lawyer. Verified specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Суд принимает только допустимые доказательства, полученные законным путём. Нарушение процедуры обесценивает даже сильные факты.", en: "Courts accept only admissible evidence obtained lawfully. Violating the procedure devalues even strong facts." } },
      { type: "h", text: { ru: "Что важно", en: "What matters" } },
      { type: "li", items: [
        { ru: "Законность способа получения", en: "Lawful method of obtaining" },
        { ru: "Правильное оформление и фиксация", en: "Proper documentation and recording" },
        { ru: "Соблюдение прав других лиц", en: "Respecting others' rights" },
      ] },
      { type: "p", text: { ru: "Детектив и юрист помогут собрать и оформить доказательства правильно. Найдите их на платформе ЩИТ.", en: "A detective and lawyer will help gather and document evidence correctly. Find them on SHCHIT." } },
    ],
  },
  {
    slug: "business-competitive-intelligence-legal",
    icon: "TrendingUp",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Конкурентная разведка: законные методы для бизнеса", en: "Competitive intelligence: legal methods for business" },
    excerpt: { ru: "Как легально изучать рынок и конкурентов, не нарушая закон и коммерческую тайну.", en: "How to legally study the market and competitors without breaking laws or trade secrets." },
    metaTitle: { ru: "Конкурентная разведка — законные методы | ЩИТ", en: "Competitive intelligence — legal methods | SHCHIT" },
    metaDescription: { ru: "Законная конкурентная разведка: открытые источники, аналитика рынка и репутации. Специалисты по экономической безопасности на платформе ЩИТ.", en: "Legal competitive intelligence: open sources, market and reputation analytics. Economic-security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Конкурентная разведка законна, если использует открытые источники и не нарушает коммерческую тайну или права людей.", en: "Competitive intelligence is legal when it uses open sources and doesn't violate trade secrets or people's rights." } },
      { type: "h", text: { ru: "Легальные источники", en: "Legal sources" } },
      { type: "li", items: [
        { ru: "Открытые реестры и публикации", en: "Open registries and publications" },
        { ru: "Публичная отчётность и новости", en: "Public reporting and news" },
        { ru: "Анализ рынка и отзывов", en: "Market and review analysis" },
      ] },
      { type: "p", text: { ru: "Специалисты по экономической безопасности проведут анализ в рамках закона. Найдите их в каталоге ЩИТ.", en: "Economic-security specialists will run the analysis within the law. Find them in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "how-to-protect-business-from-raiders",
    icon: "ShieldAlert",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как защитить бизнес от рейдерского захвата", en: "How to protect a business from a hostile takeover" },
    excerpt: { ru: "Признаки угрозы захвата бизнеса и законные меры защиты компании и активов.", en: "Signs of a takeover threat and legal measures to protect the company and assets." },
    metaTitle: { ru: "Защита бизнеса от рейдерского захвата — меры | ЩИТ", en: "Protecting a business from a hostile takeover — measures | SHCHIT" },
    metaDescription: { ru: "Как защитить компанию от рейдерского захвата: юридическая защита, безопасность документов и активов. Специалисты по корпоративной безопасности на ЩИТ.", en: "How to protect a company from a hostile takeover: legal protection, document and asset security. Corporate-security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Рейдерский захват проще предотвратить, чем отбить. Ранняя защита документов, активов и структуры компании критична.", en: "A hostile takeover is easier to prevent than to fight off. Early protection of documents, assets and company structure is critical." } },
      { type: "h", text: { ru: "Меры защиты", en: "Protective measures" } },
      { type: "li", items: [
        { ru: "Порядок в корпоративных документах", en: "Order in corporate documents" },
        { ru: "Контроль реестров и полномочий", en: "Control of registries and authorities" },
        { ru: "Юридический и экономический мониторинг", en: "Legal and economic monitoring" },
      ] },
      { type: "p", text: { ru: "Комплексную защиту выстроят специалисты по корпоративной безопасности с платформы ЩИТ.", en: "Comprehensive protection is built by corporate-security specialists from SHCHIT." } },
    ],
  },
  {
    slug: "travel-safety-abroad",
    icon: "Plane",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Безопасность в поездках за границу", en: "Safety when traveling abroad" },
    excerpt: { ru: "Как подготовиться к поездке и снизить риски в незнакомой стране.", en: "How to prepare for a trip and reduce risks in an unfamiliar country." },
    metaTitle: { ru: "Безопасность в поездках за границу — советы | ЩИТ", en: "Safety when traveling abroad — tips | SHCHIT" },
    metaDescription: { ru: "Безопасность в путешествиях: подготовка, документы, местные риски и сопровождение. Телохранители и консультанты по безопасности на платформе ЩИТ.", en: "Travel safety: preparation, documents, local risks and escort. Bodyguards and security consultants on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Незнакомая страна — новые риски. Подготовка и знание местной обстановки делают поездку безопаснее.", en: "An unfamiliar country means new risks. Preparation and local awareness make a trip safer." } },
      { type: "h", text: { ru: "Перед поездкой", en: "Before the trip" } },
      { type: "li", items: [
        { ru: "Изучить местные риски и правила", en: "Study local risks and rules" },
        { ru: "Сделать копии документов", en: "Make copies of documents" },
        { ru: "При необходимости — личное сопровождение", en: "If needed, personal escort" },
      ] },
      { type: "p", text: { ru: "Для VIP-поездок можно заказать сопровождение телохранителя. Найдите специалистов на платформе ЩИТ.", en: "For VIP trips, you can book bodyguard escort. Find specialists on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-deal-with-stalking-legally",
    icon: "Eye",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Что делать при навязчивом преследовании (сталкинге)", en: "What to do about stalking" },
    excerpt: { ru: "Законные шаги защиты, если вас преследуют: фиксация, обращение в органы, помощь специалистов.", en: "Legal protective steps if you're being stalked: documenting, reporting, specialist help." },
    metaTitle: { ru: "Что делать при сталкинге — законная защита | ЩИТ", en: "What to do about stalking — legal protection | SHCHIT" },
    metaDescription: { ru: "Навязчивое преследование: как законно зафиксировать факты, обратиться в органы и защитить себя. Помощь специалистов по безопасности на платформе ЩИТ.", en: "Stalking: how to legally document facts, report and protect yourself. Help from security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Навязчивое преследование опасно и недопустимо. Важно действовать законно: фиксировать факты и подключать компетентные органы.", en: "Stalking is dangerous and unacceptable. It's important to act legally: document the facts and involve competent authorities." } },
      { type: "h", text: { ru: "Что делать", en: "What to do" } },
      { type: "li", items: [
        { ru: "Фиксировать каждый случай (даты, сообщения)", en: "Document every incident (dates, messages)" },
        { ru: "Обратиться в правоохранительные органы", en: "Report to law enforcement" },
        { ru: "Усилить личную безопасность", en: "Strengthen personal security" },
      ] },
      { type: "p", text: { ru: "Специалисты по личной безопасности помогут выстроить защиту. Найдите их на платформе ЩИТ.", en: "Personal-safety specialists will help build protection. Find them on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-verify-online-seller",
    icon: "ShoppingCart",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как проверить продавца перед онлайн-покупкой", en: "How to verify a seller before an online purchase" },
    excerpt: { ru: "Признаки надёжного и поддельного интернет-магазина, чтобы не потерять деньги.", en: "Signs of a trustworthy and a fake online store so you don't lose money." },
    metaTitle: { ru: "Как проверить онлайн-продавца перед покупкой | ЩИТ", en: "How to verify an online seller before buying | SHCHIT" },
    metaDescription: { ru: "Проверка интернет-магазина и продавца: реквизиты, отзывы, безопасная оплата и признаки обмана. Консультация специалистов на платформе ЩИТ.", en: "Checking an online store and seller: details, reviews, safe payment and fraud signs. Specialist advice on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Поддельные магазины выглядят убедительно. Несколько проверок помогут отличить надёжного продавца от мошенника.", en: "Fake stores look convincing. A few checks help tell a reliable seller from a scammer." } },
      { type: "h", text: { ru: "На что смотреть", en: "What to look at" } },
      { type: "li", items: [
        { ru: "Реквизиты и контакты продавца", en: "Seller's details and contacts" },
        { ru: "Отзывы на независимых площадках", en: "Reviews on independent platforms" },
        { ru: "Безопасные способы оплаты", en: "Safe payment methods" },
      ] },
      { type: "p", text: { ru: "Если вы уже пострадали, специалист по кибербезопасности поможет с дальнейшими действиями. Найдите его на ЩИТ.", en: "If you've already been affected, a cybersecurity specialist will help with next steps. Find one on SHCHIT." } },
    ],
  },
  {
    slug: "vip-personal-security-basics",
    icon: "Crown",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Личная безопасность публичных и состоятельных людей", en: "Personal security for public and wealthy individuals" },
    excerpt: { ru: "Из чего складывается защита VIP-персон: анализ угроз, охрана, приватность.", en: "What VIP protection consists of: threat analysis, guards, privacy." },
    metaTitle: { ru: "Личная безопасность VIP — как организована | ЩИТ", en: "VIP personal security — how it's organized | SHCHIT" },
    metaDescription: { ru: "Безопасность публичных и состоятельных людей: оценка угроз, личная охрана, защита семьи и приватности. Проверенные телохранители на платформе ЩИТ.", en: "Security for public and wealthy people: threat assessment, personal guards, family and privacy protection. Verified bodyguards on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Публичность и достаток повышают риски. Профессиональная защита строится системно, а не только «на охраннике у двери».", en: "Being public and wealthy raises risks. Professional protection is built systematically, not just with 'a guard at the door'." } },
      { type: "h", text: { ru: "Составляющие защиты", en: "Components of protection" } },
      { type: "li", items: [
        { ru: "Анализ угроз и планирование", en: "Threat analysis and planning" },
        { ru: "Личная охрана и безопасный транспорт", en: "Personal guards and secure transport" },
        { ru: "Защита семьи и приватности", en: "Family and privacy protection" },
      ] },
      { type: "p", text: { ru: "Опытных телохранителей и консультантов по безопасности вы найдёте в каталоге ЩИТ.", en: "You'll find experienced bodyguards and security consultants in the SHCHIT catalog." } },
    ],
  },
  {
    slug: "how-to-check-employer-before-job",
    icon: "Factory",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как проверить работодателя перед трудоустройством", en: "How to check an employer before taking a job" },
    excerpt: { ru: "Как убедиться, что компания реальна и надёжна, и не попасть в мошенническую «вакансию».", en: "How to make sure a company is real and reliable and avoid a scam 'job offer'." },
    metaTitle: { ru: "Как проверить работодателя перед работой | ЩИТ", en: "How to check an employer before a job | SHCHIT" },
    metaDescription: { ru: "Проверка работодателя: реальность компании, отзывы сотрудников, признаки мошеннических вакансий. Помощь специалистов по безопасности на платформе ЩИТ.", en: "Checking an employer: company legitimacy, employee reviews, scam-vacancy signs. Help from security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Мошеннические «вакансии» выманивают деньги и данные. Проверка работодателя защищает соискателя.", en: "Scam 'job offers' extract money and data. Checking the employer protects the applicant." } },
      { type: "h", text: { ru: "Что проверить", en: "What to check" } },
      { type: "li", items: [
        { ru: "Реальность и регистрацию компании", en: "The company's legitimacy and registration" },
        { ru: "Отзывы сотрудников", en: "Employee reviews" },
        { ru: "Отсутствие «оплаты за трудоустройство»", en: "No 'payment for employment'" },
      ] },
      { type: "p", text: { ru: "Сомневаетесь — обратитесь к специалисту по проверке компаний на платформе ЩИТ.", en: "In doubt? Consult a company-verification specialist on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-recover-debt-legally",
    icon: "Coins",
    date: "2026-07-11",
    readMin: 6,
    audience: "client",
    title: { ru: "Как законно вернуть долг", en: "How to recover a debt legally" },
    excerpt: { ru: "Правовые способы взыскания долга и как детектив помогает найти активы должника.", en: "Legal ways to recover a debt and how a detective helps locate a debtor's assets." },
    metaTitle: { ru: "Как законно вернуть долг — правовые способы | ЩИТ", en: "How to recover a debt legally — lawful ways | SHCHIT" },
    metaDescription: { ru: "Законное взыскание долга: досудебные меры, суд, поиск активов должника детективом. Проверенные специалисты и юристы на платформе ЩИТ.", en: "Legal debt recovery: pre-court measures, court, locating a debtor's assets via a detective. Verified specialists and lawyers on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Долг возвращают только законными методами: переговоры, претензия, суд, исполнительное производство. Угрозы и давление недопустимы.", en: "A debt is recovered only by legal means: negotiation, a formal claim, court, enforcement. Threats and pressure are unacceptable." } },
      { type: "h", text: { ru: "Порядок действий", en: "The sequence" } },
      { type: "li", items: [
        { ru: "Досудебная претензия должнику", en: "A pre-court claim to the debtor" },
        { ru: "Обращение в суд при отказе", en: "Going to court if refused" },
        { ru: "Поиск активов должника (законно)", en: "Locating the debtor's assets (legally)" },
      ] },
      { type: "p", text: { ru: "Детектив поможет законно найти активы, а юрист — взыскать долг. Найдите их на платформе ЩИТ.", en: "A detective helps legally locate assets, and a lawyer recovers the debt. Find them on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-secure-office",
    icon: "Building",
    date: "2026-07-11",
    readMin: 5,
    audience: "client",
    title: { ru: "Как обеспечить безопасность офиса", en: "How to secure your office" },
    excerpt: { ru: "Комплекс мер безопасности офиса: доступ, видеонаблюдение, защита информации.", en: "A set of office security measures: access, CCTV, information protection." },
    metaTitle: { ru: "Безопасность офиса — комплекс мер | ЩИТ", en: "Office security — a set of measures | SHCHIT" },
    metaDescription: { ru: "Как обеспечить безопасность офиса: контроль доступа, видеонаблюдение, защита данных и сотрудников. Специалисты по безопасности на платформе ЩИТ.", en: "How to secure an office: access control, CCTV, data and staff protection. Security specialists on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Безопасность офиса — это не только замок на двери, а система: люди, техника и правила.", en: "Office security is not just a door lock but a system: people, technology and rules." } },
      { type: "h", text: { ru: "Ключевые элементы", en: "Key elements" } },
      { type: "li", items: [
        { ru: "Контроль доступа и учёт посетителей", en: "Access control and visitor logging" },
        { ru: "Видеонаблюдение и сигнализация", en: "CCTV and alarm" },
        { ru: "Защита документов и данных", en: "Document and data protection" },
      ] },
      { type: "p", text: { ru: "Аудит и настройку безопасности офиса закажите у специалистов на платформе ЩИТ.", en: "Order an office security audit and setup from specialists on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-check-charity-before-donating",
    icon: "HeartHandshake",
    date: "2026-07-11",
    readMin: 4,
    audience: "client",
    title: { ru: "Как проверить благотворительный фонд перед пожертвованием", en: "How to check a charity before donating" },
    excerpt: { ru: "Как убедиться, что фонд настоящий, и не стать жертвой поддельного сбора.", en: "How to make sure a charity is genuine and not fall for a fake fundraiser." },
    metaTitle: { ru: "Как проверить благотворительный фонд | ЩИТ", en: "How to check a charity before donating | SHCHIT" },
    metaDescription: { ru: "Проверка благотворительного фонда: регистрация, отчётность, репутация и признаки мошенничества. Помощь специалистов на платформе ЩИТ.", en: "Checking a charity: registration, reporting, reputation and fraud signs. Specialist help on SHCHIT." },
    body: [
      { type: "p", text: { ru: "Мошенники играют на сострадании. Проверка фонда защищает вашу помощь от попадания не по адресу.", en: "Fraudsters exploit compassion. Checking a charity keeps your help from going to the wrong place." } },
      { type: "h", text: { ru: "Что проверить", en: "What to check" } },
      { type: "li", items: [
        { ru: "Регистрацию и отчётность фонда", en: "The charity's registration and reporting" },
        { ru: "Прозрачность сборов и трат", en: "Transparency of fundraising and spending" },
        { ru: "Репутацию и независимые отзывы", en: "Reputation and independent reviews" },
      ] },
      { type: "p", text: { ru: "Сомневаетесь в сборе — попросите проверку у специалиста по безопасности на платформе ЩИТ.", en: "Doubt a fundraiser? Ask a security specialist to check it on SHCHIT." } },
    ],
  },
  {
    slug: "how-to-promote-detective-agency",
    icon: "Megaphone",
    date: "2026-07-11",
    readMin: 7,
    audience: "provider",
    title: { ru: "Как рекламировать детективное агентство: рабочие каналы", en: "How to advertise a detective agency: channels that work" },
    excerpt: { ru: "Где искать клиентов детективу, какие каналы продвижения работают и почему важна репутация.", en: "Where a detective finds clients, which promotion channels work and why reputation matters." },
    metaTitle: { ru: "Как рекламировать детективное агентство — гайд | ЩИТ", en: "How to advertise a detective agency — guide | SHCHIT" },
    metaDescription: { ru: "Продвижение детективного агентства: репутация, отзывы, каталоги специалистов, контент и сарафанное радио. Разместите профиль на платформе ЩИТ и получайте клиентов.", en: "Promoting a detective agency: reputation, reviews, specialist catalogs, content and word of mouth. List your profile on SHCHIT and get clients." },
    body: [
      { type: "p", text: { ru: "Детективные услуги — деликатная сфера, где клиенты выбирают по доверию. Поэтому продвижение строится вокруг репутации, а не «крикливой» рекламы.", en: "Detective services are a sensitive field where clients choose based on trust. So promotion is built around reputation, not loud advertising." } },
      { type: "h", text: { ru: "Что реально работает", en: "What actually works" } },
      { type: "li", items: [
        { ru: "Репутация и отзывы довольных клиентов", en: "Reputation and reviews from satisfied clients" },
        { ru: "Профиль в каталоге проверенных специалистов", en: "A profile in a catalog of verified specialists" },
        { ru: "Полезный контент: статьи, ответы на вопросы", en: "Useful content: articles, answering questions" },
        { ru: "Рекомендации коллег и партнёров (юристы, страховые)", en: "Referrals from colleagues and partners (lawyers, insurers)" },
      ] },
      { type: "h", text: { ru: "Почему каталог эффективнее рекламы", en: "Why a catalog beats ads" } },
      { type: "p", text: { ru: "В каталог приходят люди, которым уже нужна услуга — их не нужно «прогревать». Значок проверки и отзывы снимают главный барьер: страх нарваться на мошенника.", en: "People come to a catalog already needing the service — you don't need to 'warm them up'. A verification badge and reviews remove the main barrier: fear of hitting a scammer." } },
      { type: "p", text: { ru: "Разместите профиль на платформе ЩИТ: клиенты со всего мира находят вас сами, а вы платите только за подписку — без комиссии с заказов.", en: "List your profile on SHCHIT: clients worldwide find you themselves, and you pay only a subscription — with no commission on orders." } },
    ],
  },
  {
    slug: "where-security-specialists-find-clients",
    icon: "Target",
    date: "2026-07-11",
    readMin: 7,
    audience: "provider",
    title: { ru: "Где специалисту по безопасности искать клиентов", en: "Where a security specialist should find clients" },
    excerpt: { ru: "Обзор источников клиентов для детективов, телохранителей и экспертов по безопасности.", en: "An overview of client sources for detectives, bodyguards and security experts." },
    metaTitle: { ru: "Где искать клиентов специалисту по безопасности | ЩИТ", en: "Where a security specialist finds clients | SHCHIT" },
    metaDescription: { ru: "Источники клиентов для специалистов по безопасности: каталоги, рекомендации, партнёрства и репутация. Получайте заявки напрямую на платформе ЩИТ без комиссии.", en: "Client sources for security specialists: catalogs, referrals, partnerships and reputation. Get requests directly on SHCHIT with no commission." },
    body: [
      { type: "p", text: { ru: "Стабильный поток клиентов — это система из нескольких источников, а не один канал. Разберём, что даёт результат.", en: "A steady client flow is a system of several sources, not a single channel. Let's see what delivers results." } },
      { type: "h", text: { ru: "Основные источники клиентов", en: "Main client sources" } },
      { type: "li", items: [
        { ru: "Специализированные каталоги и площадки", en: "Specialized catalogs and platforms" },
        { ru: "Рекомендации и повторные обращения", en: "Referrals and repeat clients" },
        { ru: "Партнёрства с юристами и страховыми", en: "Partnerships with lawyers and insurers" },
        { ru: "Личный бренд и экспертный контент", en: "Personal brand and expert content" },
      ] },
      { type: "h", text: { ru: "Как получать заявки без рекламного бюджета", en: "How to get requests without an ad budget" } },
      { type: "p", text: { ru: "Разместите профиль там, где клиенты уже ищут специалистов. На платформе ЩИТ клиенты оставляют заявки, а вы отвечаете напрямую — без посредников и комиссии с заказов.", en: "Place your profile where clients already search for specialists. On SHCHIT clients submit requests and you respond directly — no intermediaries, no order commission." } },
      { type: "p", text: { ru: "Международный охват платформы означает клиентов из разных стран и постоянный поток заявок по вашей специализации.", en: "The platform's international reach means clients from different countries and a steady flow of requests in your specialization." } },
    ],
  },
  {
    slug: "how-to-build-reputation-detective",
    icon: "Star",
    date: "2026-07-11",
    readMin: 6,
    audience: "provider",
    title: { ru: "Как построить репутацию и получать больше заказов", en: "How to build reputation and get more orders" },
    excerpt: { ru: "Репутация — главный актив специалиста по безопасности. Как её выстроить системно.", en: "Reputation is a security specialist's main asset. How to build it systematically." },
    metaTitle: { ru: "Как построить репутацию специалиста по безопасности | ЩИТ", en: "How to build a security specialist's reputation | SHCHIT" },
    metaDescription: { ru: "Как выстроить репутацию детектива или охранного специалиста: отзывы, кейсы, верификация и профессионализм. Собирайте отзывы и рейтинг на платформе ЩИТ.", en: "How to build a detective's or security specialist's reputation: reviews, cases, verification and professionalism. Collect reviews and rating on SHCHIT." },
    body: [
      { type: "p", text: { ru: "В сфере безопасности клиент рискует деньгами и личными данными, поэтому выбирает по доверию. Репутация напрямую влияет на доход.", en: "In security, a client risks money and personal data, so they choose based on trust. Reputation directly affects income." } },
      { type: "h", text: { ru: "Как усилить репутацию", en: "How to strengthen reputation" } },
      { type: "li", items: [
        { ru: "Собирать отзывы после каждого дела", en: "Collect reviews after every case" },
        { ru: "Пройти верификацию документов и лицензии", en: "Complete document and license verification" },
        { ru: "Показывать кейсы (без раскрытия тайны клиента)", en: "Show cases (without revealing client confidentiality)" },
        { ru: "Быстро и профессионально отвечать на заявки", en: "Respond to requests quickly and professionally" },
      ] },
      { type: "p", text: { ru: "На платформе ЩИТ верификация даёт значок «Лицензия», а система отзывов и рейтинга формирует доверие ещё до первого разговора с клиентом.", en: "On SHCHIT verification grants a 'License' badge, and the review-and-rating system builds trust before the first conversation with a client." } },
      { type: "p", text: { ru: "Чем выше рейтинг и больше отзывов — тем чаще клиенты выбирают именно вас.", en: "The higher your rating and the more reviews, the more often clients choose you." } },
    ],
  },
  {
    slug: "how-to-price-detective-services",
    icon: "Wallet",
    date: "2026-07-11",
    readMin: 6,
    audience: "provider",
    title: { ru: "Как формировать цены на услуги и не терять клиентов", en: "How to price your services without losing clients" },
    excerpt: { ru: "Подходы к ценообразованию в детективных и охранных услугах: как оценить работу справедливо.", en: "Pricing approaches in detective and security services: how to value your work fairly." },
    metaTitle: { ru: "Как формировать цены на детективные услуги | ЩИТ", en: "How to price detective services | SHCHIT" },
    metaDescription: { ru: "Ценообразование в услугах безопасности: форматы оплаты, прозрачность, ценность для клиента. Оставляйте себе 100% дохода на платформе ЩИТ без комиссии с заказов.", en: "Pricing in security services: payment formats, transparency, client value. Keep 100% of earnings on SHCHIT with no order commission." },
    body: [
      { type: "p", text: { ru: "Правильная цена отражает ценность и опыт, но остаётся понятной клиенту. Прозрачность повышает доверие и конверсию в заказ.", en: "The right price reflects value and experience while staying clear to the client. Transparency raises trust and conversion into an order." } },
      { type: "h", text: { ru: "Что учесть в цене", en: "What to factor into price" } },
      { type: "li", items: [
        { ru: "Сложность и риски задачи", en: "Task complexity and risks" },
        { ru: "Ваш опыт и квалификацию", en: "Your experience and qualifications" },
        { ru: "Формат: почасово, за проект, абонемент", en: "Format: hourly, per project, retainer" },
      ] },
      { type: "p", text: { ru: "Важно: скрытые доплаты разрушают доверие. Указывайте прозрачные условия — клиенты это ценят.", en: "Important: hidden surcharges destroy trust. State transparent terms — clients value it." } },
      { type: "p", text: { ru: "На платформе ЩИТ нет комиссии с заказов: весь доход остаётся у вас, вы платите только фиксированную подписку. Это позволяет держать честные цены и зарабатывать больше.", en: "On SHCHIT there's no commission on orders: you keep all the income and pay only a fixed subscription. This lets you keep fair prices and earn more." } },
    ],
  },
  {
    slug: "why-join-shchit-platform",
    icon: "Rocket",
    date: "2026-07-11",
    readMin: 6,
    audience: "provider",
    title: { ru: "Почему специалисту стоит разместиться на платформе ЩИТ", en: "Why a specialist should join the SHCHIT platform" },
    excerpt: { ru: "Что даёт специалисту по безопасности профиль на международной платформе проверенных экспертов.", en: "What a profile on an international platform of verified experts gives a security specialist." },
    metaTitle: { ru: "Почему стоит разместиться на платформе ЩИТ | ЩИТ", en: "Why join the SHCHIT platform | SHCHIT" },
    metaDescription: { ru: "Преимущества платформы ЩИТ для специалистов: клиенты без рекламы, 0% комиссии с заказов, международный охват, верификация и сообщество. Разместите профиль бесплатно.", en: "SHCHIT benefits for specialists: clients without ads, 0% order commission, international reach, verification and community. Create your profile." },
    body: [
      { type: "p", text: { ru: "Найти клиентов в сфере безопасности сложно: реклама дорогая, а доверие завоёвывается годами. Платформа проверенных специалистов решает обе проблемы сразу.", en: "Finding clients in security is hard: ads are expensive and trust takes years to earn. A platform of verified specialists solves both problems at once." } },
      { type: "h", text: { ru: "Что вы получаете", en: "What you get" } },
      { type: "li", items: [
        { ru: "Клиенты находят вас сами — без затрат на рекламу", en: "Clients find you themselves — with no ad spend" },
        { ru: "0% комиссии с заказов — весь доход ваш", en: "0% order commission — all income is yours" },
        { ru: "Международный поток заявок по вашей теме", en: "An international flow of requests in your field" },
        { ru: "Верификация и значок «Лицензия» для доверия", en: "Verification and a 'License' badge for trust" },
        { ru: "Профессиональное сообщество и обмен опытом", en: "A professional community and experience sharing" },
      ] },
      { type: "p", text: { ru: "Вы платите только за подписку по фиксированному тарифу — без процентов со сделок и скрытых платежей. Это выгоднее классической рекламы и посредников.", en: "You pay only a fixed subscription — no deal percentages and no hidden fees. It's more profitable than classic advertising and intermediaries." } },
      { type: "p", text: { ru: "Создайте профиль на платформе ЩИТ, пройдите верификацию — и начните получать заявки от клиентов уже сегодня.", en: "Create your profile on SHCHIT, get verified — and start receiving client requests today." } },
    ],
  },
];