// Каталог категорий и услуг платформы — статичные данные, вынесены из Index.tsx,
// чтобы страница не раздувалась и правки в ней были дешевле.
export type ServiceCategory = { id: string; icon: string; title: { ru: string; en: string } };

export const serviceCategories = [
  { id: "physical", icon: "ShieldCheck", title: { ru: "Физическая безопасность и личная охрана", en: "Physical security & close protection" } },
  { id: "cyber", icon: "Lock", title: { ru: "Информационная и кибербезопасность", en: "Information & cybersecurity" } },
  { id: "economic", icon: "Briefcase", title: { ru: "Экономическая безопасность, комплаенс и расследования", en: "Economic security, compliance & investigations" } },
  { id: "crisis", icon: "Siren", title: { ru: "Антикризисное управление и спецоперации", en: "Crisis management & special operations" } },
] as const;

export const services = [
  // Физическая безопасность и личная охрана
  { cat: "physical", icon: "Eye", title: { ru: "Частный детектив", en: "Private investigator" }, price: { ru: "от 12 000 ₽/день", en: "from $140/day" }, time: { ru: "от 1 дня", en: "from 1 day" }, desc: { ru: "Сыщик, агент наружного наблюдения: поиск людей, проверка фактов, слежка по поручению клиента", en: "Investigator and surveillance agent: locating people, fact-checking and shadowing for clients" } },
  { cat: "physical", icon: "UserCog", title: { ru: "Телохранитель / оператор личной охраны", en: "Executive protection agent" }, price: { ru: "от 9 000 ₽/смена", en: "from $100/shift" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Бодигард, прикреплённый секьюрити: непосредственная защита VIP, руководителя, публичной персоны", en: "Bodyguard and close-protection officer for VIPs, executives and public figures" } },
  { cat: "physical", icon: "RadioTower", title: { ru: "Специалист по технической защите информации (TSCM)", en: "TSCM specialist" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "от 4 часов", en: "from 4 hours" }, desc: { ru: "Искатель жучков, антишпион: поиск закладок, деактивация прослушки, экранирование помещений", en: "Bug-sweeper and counter-surveillance expert: finding taps and shielding rooms" } },
  { cat: "physical", icon: "Activity", title: { ru: "Полиграфолог", en: "Polygraph examiner" }, price: { ru: "от 8 000 ₽", en: "from $90" }, time: { ru: "2–3 часа", en: "2–3 hours" }, desc: { ru: "Детектор лжи, верификатор: проверки для бизнеса и частных лиц — HR, расследования, благонадёжность", en: "Lie-detection and verification: HR checks, investigations and trustworthiness screening" } },
  { cat: "physical", icon: "Bomb", title: { ru: "Специалист по поиску взрывчатых веществ (EOD)", en: "EOD technician" }, price: { ru: "по запросу", en: "on request" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Сапёр, эксперт по ВВ: обнаружение и обезвреживание взрывоопасных предметов", en: "Bomb-disposal expert: detection and neutralization of explosive devices" } },
  { cat: "physical", icon: "Cctv", title: { ru: "Оператор центра мониторинга физической безопасности", en: "Physical security monitoring operator" }, price: { ru: "от 180 ₽/час", en: "from $2/hour" }, time: { ru: "24/7", en: "24/7" }, desc: { ru: "Дежурный аналитик камер, смотритель логов СКУД: контроль видеонаблюдения и доступа в реальном времени", en: "CCTV analyst and access-log monitor: real-time video and access control" } },
  { cat: "physical", icon: "Route", title: { ru: "Специалист по безопасности маршрутов", en: "Route planning specialist" }, price: { ru: "от 15 000 ₽", en: "from $170" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Разведчик дорог, водитель-каскадер: планирование безопасных маршрутов и защитное вождение", en: "Route scout and evasive driver: safe-route planning and defensive driving" } },
  { cat: "physical", icon: "Dog", title: { ru: "Кинолог-профайлер (специалист по досмотру)", en: "K9 screening handler" }, price: { ru: "от 12 000 ₽", en: "from $140" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Оператор служебной собаки: поиск взрывчатки, запрещённых веществ, досмотр на объектах", en: "Service-dog handler: explosives and contraband detection, facility screening" } },
  { cat: "physical", icon: "Radar", title: { ru: "Оператор нелетальных систем противодействия", en: "Non-lethal countermeasures operator" }, price: { ru: "по запросу", en: "on request" }, time: { ru: "под событие", en: "per event" }, desc: { ru: "Установщик акустических пушек (LRAD), антидрон-сеток и систем нелетального противодействия", en: "Operator of acoustic devices (LRAD) and anti-drone nets" } },

  // Информационная и кибербезопасность
  { cat: "cyber", icon: "KeyRound", title: { ru: "Пентестер физических объектов", en: "Physical penetration tester" }, price: { ru: "от 40 000 ₽", en: "from $450" }, time: { ru: "от 1 недели", en: "from 1 week" }, desc: { ru: "Обходчик замков, тестер бдительности охраны: санкционированное проникновение на объекты", en: "Lock-bypass and guard-awareness testing: authorized physical intrusion" } },
  { cat: "cyber", icon: "FileSearch", title: { ru: "Эксперт-криминалист цифровой информации", en: "Digital forensics examiner" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "3–10 дней", en: "3–10 days" }, desc: { ru: "IT-следователь, восстановитель данных: сбор цифровых улик и восстановление хронологии событий", en: "IT investigator: data recovery and digital evidence collection" } },
  { cat: "cyber", icon: "ScanFace", title: { ru: "Аналитик поведенческого профайлинга", en: "Behavioral detection officer" }, price: { ru: "от 18 000 ₽", en: "from $200" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Чтец микровыражений, наблюдатель за угрозами в толпе: выявление подозрительного поведения", en: "Micro-expression reader and crowd-threat observer" } },
  { cat: "cyber", icon: "Globe", title: { ru: "OSINT-аналитик", en: "OSINT analyst" }, price: { ru: "от 15 000 ₽", en: "from $170" }, time: { ru: "2–5 дней", en: "2–5 days" }, desc: { ru: "Сетевой следопыт, диджитал-детектив: разведка по открытым источникам и проверка контрагентов", en: "Digital tracker: open-source intelligence and counterparty checks" } },
  { cat: "cyber", icon: "ShieldAlert", title: { ru: "Фрод-аналитик / антифрод-менеджер", en: "Fraud prevention analyst" }, price: { ru: "от 30 000 ₽", en: "from $340" }, time: { ru: "проект", en: "project" }, desc: { ru: "Охотник за кардерами, ловец ботов: выявление и предотвращение мошеннических операций", en: "Anti-fraud specialist: detecting carders and bots, preventing fraud" } },
  { cat: "cyber", icon: "Activity", title: { ru: "Менеджер центра мониторинга ИБ (SOC)", en: "SOC analyst" }, price: { ru: "от 25 000 ₽/мес", en: "from $280/mo" }, time: { ru: "24/7 мониторинг", en: "24/7 monitoring" }, desc: { ru: "Сторож логов, дежурный по инцидентам: мониторинг событий и реагирование в реальном времени", en: "Log guardian: real-time monitoring and incident response" } },
  { cat: "cyber", icon: "Cloud", title: { ru: "Архитектор облачной безопасности", en: "Cloud security engineer" }, price: { ru: "от 45 000 ₽", en: "from $500" }, time: { ru: "проект", en: "project" }, desc: { ru: "Настройщик прав доступа, защитник виртуальных серверов и облачных хранилищ", en: "Access-permissions architect and cloud-server defender" } },
  { cat: "cyber", icon: "Factory", title: { ru: "Инженер по безопасности промышленных систем (ICS/OT)", en: "ICS/OT security specialist" }, price: { ru: "от 50 000 ₽", en: "from $550" }, time: { ru: "проект", en: "project" }, desc: { ru: "Защитник умного завода, страж станков с ЧПУ и АСУ ТП: безопасность промышленной автоматики", en: "Smart-factory protector: securing CNC machines and industrial control systems" } },
  { cat: "cyber", icon: "Fingerprint", title: { ru: "Специалист по биометрической идентификации", en: "Biometric identification specialist" }, price: { ru: "от 30 000 ₽", en: "from $340" }, time: { ru: "проект", en: "project" }, desc: { ru: "Мастер сканеров лица и отпечатков: внедрение и защита систем биометрического доступа", en: "Face- and fingerprint-scanner expert: biometric access systems" } },
  { cat: "cyber", icon: "Volume2", title: { ru: "Специалист по акустической защите помещений", en: "Acoustic protection specialist" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "от 4 часов", en: "from 4 hours" }, desc: { ru: "Глушитель звука, подавитель лазерного съёма со стёкол: защита переговоров от прослушивания", en: "Sound-masking and anti-laser-eavesdropping protection of meeting rooms" } },
  { cat: "cyber", icon: "Cpu", title: { ru: "Специалист по безопасности Интернета вещей (IoT)", en: "IoT security specialist" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "проект", en: "project" }, desc: { ru: "Антивирус для умных устройств и турбин: защита IoT-инфраструктуры от взлома", en: "Protecting smart devices and industrial IoT from compromise" } },
  { cat: "cyber", icon: "KeySquare", title: { ru: "Администратор привилегированного доступа (PAM)", en: "PAM administrator" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "проект", en: "project" }, desc: { ru: "Ключник, хранитель паролей администраторов: управление привилегированными учётными записями", en: "Keeper of admin credentials: privileged access management" } },
  { cat: "cyber", icon: "Boxes", title: { ru: "Аудитор безопасности цепочек поставок ПО", en: "Supply chain security auditor" }, price: { ru: "от 40 000 ₽", en: "from $450" }, time: { ru: "1–3 недели", en: "1–3 weeks" }, desc: { ru: "Проверяльщик библиотек, санитар софта: аудит зависимостей и поставщиков программного обеспечения", en: "Software-dependency and vendor auditor for supply-chain risks" } },
  { cat: "cyber", icon: "BrainCircuit", title: { ru: "Специалист по безопасности нейросетей (AI Red Team)", en: "AI red teamer" }, price: { ru: "от 50 000 ₽", en: "from $550" }, time: { ru: "проект", en: "project" }, desc: { ru: "Обманщик автопилота, тестер моделей: атаки на ИИ и защита от отравления данных", en: "AI adversarial testing: attacks on models and data-poisoning defense" } },
  { cat: "cyber", icon: "Bitcoin", title: { ru: "Специалист по крипто-форензике", en: "Blockchain forensics investigator" }, price: { ru: "от 40 000 ₽", en: "from $450" }, time: { ru: "3–10 дней", en: "3–10 days" }, desc: { ru: "Распутыватель транзакций, деанонимайзер: отслеживание криптовалют и блокчейн-расследования", en: "Crypto-transaction tracing and blockchain investigations" } },
  { cat: "cyber", icon: "Atom", title: { ru: "Специалист по постквантовой криптографии", en: "Post-quantum cryptography specialist" }, price: { ru: "от 55 000 ₽", en: "from $600" }, time: { ru: "проект", en: "project" }, desc: { ru: "Архитектор шифров будущего: внедрение алгоритмов, устойчивых к квантовым вычислениям", en: "Architect of quantum-resistant encryption" } },
  { cat: "cyber", icon: "GraduationCap", title: { ru: "Специалист по кибергигиене (Security Awareness)", en: "Security awareness manager" }, price: { ru: "от 20 000 ₽", en: "from $230" }, time: { ru: "проект", en: "project" }, desc: { ru: "Анти-фишинг коуч, тренер SecOps: обучение сотрудников безопасному поведению", en: "Anti-phishing coach: staff security-awareness training" } },
  { cat: "cyber", icon: "VideoOff", title: { ru: "Специалист по защите от дипфейков", en: "Deepfake forensics expert" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "2–7 дней", en: "2–7 days" }, desc: { ru: "Распознаватель подделок: экспертиза видео и аудио на предмет синтетических фальсификаций", en: "Detecting synthetic video and audio forgeries" } },
  { cat: "cyber", icon: "Fingerprint", title: { ru: "Специалист по поведенческой биометрике (UBA)", en: "UBA analyst" }, price: { ru: "от 30 000 ₽", en: "from $340" }, time: { ru: "проект", en: "project" }, desc: { ru: "Детектор цифрового почерка: анализ поведения пользователей для выявления аномалий", en: "Digital-behavior analyst: user behavior analytics for anomaly detection" } },

  // Экономическая безопасность, комплаенс и расследования
  { cat: "economic", icon: "Banknote", title: { ru: "Специалист по экономической безопасности", en: "Corporate security manager" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "проект", en: "project" }, desc: { ru: "Корпоративный контрразведчик, СБшник: предотвращение мошенничества, хищений и коррупции", en: "Corporate counter-intelligence: preventing fraud, theft and corruption" } },
  { cat: "economic", icon: "UserSearch", title: { ru: "Дью-дил исследователь / комплаенс-скрининг", en: "Due diligence investigator" }, price: { ru: "от 20 000 ₽", en: "from $230" }, time: { ru: "3–10 дней", en: "3–10 days" }, desc: { ru: "Проверка топ-менеджеров и контрагентов, поиск компромата перед сделками и наймом", en: "Background screening of executives and counterparties before deals and hiring" } },
  { cat: "economic", icon: "Copyright", title: { ru: "Специалист по защите бренда и интеллектуальной собственности", en: "Brand protection manager" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "проект", en: "project" }, desc: { ru: "Борец с контрафактом, защитник товарного знака: мониторинг подделок и незаконного использования", en: "Anti-counterfeit and trademark protection" } },
  { cat: "economic", icon: "Scale", title: { ru: "Юрисконсульт по вопросам безопасности", en: "Security legal counsel" }, price: { ru: "от 20 000 ₽", en: "from $230" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Легалайзер расследований, адвокат для охранных структур: правовое сопровождение безопасности", en: "Legal support for investigations and security operations" } },
  { cat: "economic", icon: "SearchCheck", title: { ru: "Корпоративный следователь / фрод-эксперт", en: "Internal investigator" }, price: { ru: "от 20 000 ₽", en: "from $230" }, time: { ru: "3–10 дней", en: "3–10 days" }, desc: { ru: "Искатель откатов, ревизор под прикрытием: внутренние расследования мошенничества и краж", en: "Internal fraud and theft investigations" } },
  { cat: "economic", icon: "FileLock", title: { ru: "DPO / консультант по защите персональных данных", en: "Data protection officer" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "проект", en: "project" }, desc: { ru: "Специалист по GDPR и 152-ФЗ: приведение обработки данных в соответствие требованиям закона", en: "GDPR/privacy compliance and data-processing audits" } },
  { cat: "economic", icon: "LifeBuoy", title: { ru: "BCP/DRP-менеджер (непрерывность бизнеса)", en: "Business continuity planner" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "проект", en: "project" }, desc: { ru: "Планировщик действий при ЧС: планы непрерывности бизнеса и восстановления после сбоев", en: "Business continuity and disaster-recovery planning" } },
  { cat: "economic", icon: "Container", title: { ru: "Специалист по безопасности цепей поставок грузов", en: "Cargo ISPS coordinator" }, price: { ru: "от 30 000 ₽", en: "from $340" }, time: { ru: "проект", en: "project" }, desc: { ru: "Логист-секьюрити: защита фур, контейнеров и грузовых потоков от хищений и рисков", en: "Cargo and container security across the logistics chain" } },
  { cat: "economic", icon: "Fingerprint", title: { ru: "Судебный криминалист-трасолог", en: "Forensic evidence collection specialist" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Ловец отпечатков, фиксатор следов взлома: сбор и оформление вещественных доказательств", en: "Collecting fingerprints and physical break-in evidence" } },
  { cat: "economic", icon: "Bitcoin", title: { ru: "Блокчейн-аналитик AML", en: "Cryptocurrency compliance specialist" }, price: { ru: "от 35 000 ₽", en: "from $400" }, time: { ru: "2–7 дней", en: "2–7 days" }, desc: { ru: "Проверка чистоты криптокошельков перед сделкой, комплаенс по противодействию отмыванию", en: "AML checks and wallet-purity screening before deals" } },

  // Антикризисное управление и специальные операции
  { cat: "crisis", icon: "Siren", title: { ru: "Координатор экстренной эвакуации", en: "Evacuation coordinator" }, price: { ru: "по запросу", en: "on request" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Кризисный логист: организация вывоза людей из зон конфликтов и чрезвычайных ситуаций", en: "Crisis logistics: evacuation from conflict and emergency zones" } },
  { cat: "crisis", icon: "Handshake", title: { ru: "Переговорщик по освобождению заложников (K&R)", en: "K&R consultant" }, price: { ru: "по запросу", en: "on request" }, time: { ru: "по запросу", en: "on request" }, desc: { ru: "Консультант страховых компаний, переговорщик: разрешение похищений и вымогательств", en: "Kidnap-and-ransom negotiation and consulting" } },
  { cat: "crisis", icon: "Megaphone", title: { ru: "Пресс-секретарь в кризисных ситуациях", en: "On-scene spokesperson" }, price: { ru: "от 25 000 ₽", en: "from $280" }, time: { ru: "под событие", en: "per event" }, desc: { ru: "Гаситель скандалов, дипломат при инцидентах: коммуникации со СМИ в острых ситуациях", en: "Crisis communications and media relations during incidents" } },
  { cat: "crisis", icon: "UserRoundCog", title: { ru: "Эмулятор угроз человеческого фактора", en: "Social engineering specialist" }, price: { ru: "от 30 000 ₽", en: "from $340" }, time: { ru: "от 1 недели", en: "from 1 week" }, desc: { ru: "Этичный социальный инженер: проверка устойчивости персонала к манипуляциям и обману", en: "Ethical social engineering: testing staff resistance to manipulation" } },
  { cat: "crisis", icon: "HeartPulse", title: { ru: "Специалист по медицинской кибербезопасности", en: "Medical device security specialist" }, price: { ru: "от 45 000 ₽", en: "from $500" }, time: { ru: "проект", en: "project" }, desc: { ru: "Защитник кардиостимуляторов и инсулиновых помп: безопасность медицинских приборов", en: "Securing pacemakers, insulin pumps and medical devices" } },
  { cat: "crisis", icon: "TriangleAlert", title: { ru: "Аудитор уязвимости критической инфраструктуры", en: "Vulnerability assessment specialist" }, price: { ru: "от 50 000 ₽", en: "from $550" }, time: { ru: "1–3 недели", en: "1–3 weeks" }, desc: { ru: "Эксперт по техногенным авариям: аудит ТЭЦ, заводов и объектов критической инфраструктуры", en: "Critical-infrastructure and industrial-hazard vulnerability audits" } },
];
